[package]
name = "pollock"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.43.0"

[package.metadata.component]
package = "halleyre:pollock"
[package.metadata.component.dependencies]
