package halleyre:pollock@0.0.1;

world legocity {
    import web-elements: interface {
        alert: func(msg: string);
    }
    export legocity: func(name: string);
    export run: func() -> result<string, string>;
}
